server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Mọi request đều trả về index.html để Angular tự xử lý Routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bỏ qua logs cho các tài nguyên tĩnh
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
